# Generated by Django 4.1.6 on 2023-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="field",
            new_name="blog_category",
        ),
        migrations.AddField(
            model_name="author",
            name="field_of_study",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
